//
//  FolderShowInteractor.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Business Logic protocols
protocol FolderShowBusinessLogic {
    func folderLoadContext(withRequestModel requestModel: FolderShowModels.Folder.RequestModel)
}

protocol FolderShowDataStore {
    var folderURL: URL { get set }
}

class FolderShowInteractor: FolderShowBusinessLogic, FolderShowDataStore {
    // MARK: - Properties
    var presenter: FolderShowPresentationLogic?
    var worker: FolderShowWorker?

    var folderURL: URL = URL(fileURLWithPath: "")

    
    // MARK: - Business logic implementation
    func folderLoadContext(withRequestModel requestModel: FolderShowModels.Folder.RequestModel) {
        worker = FolderShowWorker()
        
        worker?.folderContextLoad({ filesArray in
            let responseModel = FolderShowModels.Folder.ResponseModel(files: filesArray)
            self.presenter?.presentSomething(response: responseModel)
        })
    }
}
