//
//  FolderShowWorker.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa
import FilesProvider

class FolderShowWorker {
    // MARK: - Business Logic
    func loadFolderContext(forPage page: UInt, completion: @escaping (_ data: [FileObject]) -> ()) {
        // Get list of files in a directory
        FolderManager.instance.fileProvider.contentsOfDirectory(path: "/", completionHandler: { contents, error in
            var files = [FileObject]()
            let start = contents.count >= Int(page * pageRows) ? Int(page * pageRows) : nil
            let finish = contents.count >= Int(page * pageRows + pageRows) ? Int(page * pageRows + pageRows) : contents.count - 1
            
            if start != nil {
                for file in contents[start!...finish] {
                    files.append(file)
                }
            }
            
            completion(files)
//            completion(files.filter({!$0.name.hasPrefix(".")}))
        })
    }
}
