//
//  FolderShowPresenter.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Presentation Logic protocols
protocol FolderShowPresentationLogic {
    func presentSomething(response: FolderShowModels.Something.ResponseModel)
}

class FolderShowPresenter: FolderShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: FolderShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: FolderShowModels.Something.ResponseModel) {
        let viewModel = FolderShowModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
