//
//  FolderShowPresenter.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Presentation Logic protocols
protocol FolderShowPresentationLogic {
    func presentLoadFolderContext(fromResponseModel responseModel: FolderShowModels.Folder.ResponseModel)
}

class FolderShowPresenter: FolderShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: FolderShowDisplayLogic?
    
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.dateFormat = "dd.MM.yyyy"
        
        return dateFormatter
    }()

    
    // MARK: - Presentation Logic implementation
    func presentLoadFolderContext(fromResponseModel responseModel: FolderShowModels.Folder.ResponseModel) {
        // Prepare to present DisplayedFolder models
        var models = [FolderShowModels.Folder.ViewModel.DisplayedFolder]()
        
        for file in responseModel.files {
            
            models.append(FolderShowModels.Folder.ViewModel.DisplayedFolder(name: file.name,
                                                                            size: ByteCountFormatter().string(fromByteCount: file.size),
                                                                            modifyDate: dateFormatter.string(from: file.modifiedDate!),
                                                                            path: file.path,
                                                                            isFolder: file.isDirectory))
        }
        
        let viewModel = FolderShowModels.Folder.ViewModel(displayedFolders: models)
        viewController?.displayLoadFolderContext(fromViewModel: viewModel)
    }
}
