//
//  FolderShowModels.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa
import FilesProvider

// MARK: - Data models
enum FolderShowModels {
    // MARK: - Use cases
    enum Folder {
        struct RequestModel {
            let pageNumber: UInt
        }
        
        struct ResponseModel {
            let files: [FileObject]
        }
        
        struct ViewModel {
            struct DisplayedFolder {
                var name: String
                var size: String
                var modifyDate: String
                var ext: String
                var isFolder: Bool
            }
            
            var displayedFolders: [DisplayedFolder]
        }
    }
}
