//
//  FolderShowInteractor.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Business Logic protocols
protocol FolderShowBusinessLogic {
    func loadFolderContext(withRequestModel requestModel: FolderShowModels.Folder.RequestModel)
}

protocol FolderShowDataStore {}

class FolderShowInteractor: FolderShowBusinessLogic, FolderShowDataStore {
    // MARK: - Properties
    var presenter: FolderShowPresentationLogic?
    var worker: FolderShowWorker?

    
    // MARK: - Business logic implementation
    func loadFolderContext(withRequestModel requestModel: FolderShowModels.Folder.RequestModel) {
        worker = FolderShowWorker()
        
        // Load selected folder context & send to Presenter
        worker?.loadFolderContext(forPage: requestModel.pageNumber, completion: { filesArray in
            let responseModel = FolderShowModels.Folder.ResponseModel(files: filesArray)
            self.presenter?.presentLoadFolderContext(fromResponseModel: responseModel)
        })
    }
}
