//
//  FolderShowRouter.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Input & Output protocols
@objc protocol FolderShowRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FolderShowDataPassing {
    var dataStore: FolderShowDataStore? { get }
}

class FolderShowRouter: NSObject, FolderShowRoutingLogic, FolderShowDataPassing {
    // MARK: - Properties
    weak var viewController: FolderShowViewController?
    var dataStore: FolderShowDataStore?
    
    
    // MARK: - Routing
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    
    // MARK: - Navigation
    //func navigateToSomewhere(source: FolderShowViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}
    
    
    // MARK: - Passing data
    //func passDataToSomewhere(source: FolderShowDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
