//
//  QuestionShowInteractor.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Business Logic protocols
protocol QuestionShowBusinessLogic {
    func folderDidLoad(withRequestModel requestModel: QuestionShowModels.Folder.RequestModel)
}

protocol QuestionShowDataStore {
    //var name: String { get set }
}

class QuestionShowInteractor: QuestionShowBusinessLogic, QuestionShowDataStore {
    // MARK: - Properties
    var presenter: QuestionShowPresentationLogic?
    var worker: QuestionShowWorker?
    //var name: String = ""
    
    
    // MARK: - Business logic implementation
    func folderDidLoad(withRequestModel requestModel: QuestionShowModels.Folder.RequestModel) {
        worker = QuestionShowWorker()
        worker?.doSomeWork()
        
        let responseModel = QuestionShowModels.Folder.ResponseModel()
        presenter?.presentSomething(response: responseModel)
    }
}
