//
//  QuestionShowPresenter.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Presentation Logic protocols
protocol QuestionShowPresentationLogic {
    func presentSomething(response: QuestionShowModels.Folder.ResponseModel)
}

class QuestionShowPresenter: QuestionShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: QuestionShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: QuestionShowModels.Folder.ResponseModel) {
        let viewModel = QuestionShowModels.Folder.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
