//
//  QuestionShowInteractor.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Business Logic protocols
protocol QuestionShowBusinessLogic {
    func folderLoad(withRequestModel requestModel: QuestionShowModels.Folder.RequestModel)
}

protocol QuestionShowDataStore {
    var folderURL: URL? { get set }
}

class QuestionShowInteractor: QuestionShowBusinessLogic, QuestionShowDataStore {
    // MARK: - Properties
    var presenter: QuestionShowPresentationLogic?
    var worker: QuestionShowWorker?
    
    var folderURL: URL?

    
    // MARK: - Business logic implementation
    func folderLoad(withRequestModel requestModel: QuestionShowModels.Folder.RequestModel) {
        worker = QuestionShowWorker()
        
        let isFolderExists = worker!.folderExists(atPath: requestModel.path)
        folderURL = isFolderExists ? URL(fileURLWithPath: requestModel.path) : nil
        let responseModel = QuestionShowModels.Folder.ResponseModel(isFolderExists: isFolderExists)
        presenter?.folderPreparePresentLoad(fromResponseModel: responseModel)
    }
}
