//
//  QuestionShowModels.swift
//  FolderOdessaDemo
//
//  Created by msm72 on 04.10.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Cocoa

// MARK: - Data models
enum QuestionShowModels {
    // MARK: - Use cases
    enum Folder {
        struct RequestModel {
            let path: String
        }
        
        struct ResponseModel {
            var isFolderExists: Bool
        }
        
        struct ViewModel {
            var isFolderExists: Bool
        }
    }
}
